import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{listStyle: "none", padding: "0"}}>
        <li style={{marginBottom: "10px"}}>
          <Link to="/" style={{color: "#87CEFA", textDecoration: "none"}}>
            LandingPage
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/login" style={{color: "#87CEFA", textDecoration: "none"}}>
            Login
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/create-account" style={{color: "#87CEFA", textDecoration: "none"}}>
            Create Account
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/aboutus" style={{color: "#87CEFA", textDecoration: "none"}}>
            AboutUs
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/listing" style={{color: "#87CEFA", textDecoration: "none"}}>
            Listing
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/listingmapview" style={{color: "#87CEFA", textDecoration: "none"}}>
            ListingMapView
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/propertydetails" style={{color: "#87CEFA", textDecoration: "none"}}>
            PropertyDetails
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/agentlist" style={{color: "#87CEFA", textDecoration: "none"}}>
            AgentList
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/agentprofile" style={{color: "#87CEFA", textDecoration: "none"}}>
            AgentProfile
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/contactpage" style={{color: "#87CEFA", textDecoration: "none"}}>
            ContactPage
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/blogpage" style={{color: "#87CEFA", textDecoration: "none"}}>
            BlogPage
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/blogdetails" style={{color: "#87CEFA", textDecoration: "none"}}>
            BlogDetails
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/error" style={{color: "#87CEFA", textDecoration: "none"}}>
            Error
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/faq" style={{color: "#87CEFA", textDecoration: "none"}}>
            FAQ
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/privacypolicy" style={{color: "#87CEFA", textDecoration: "none"}}>
            PrivacyPolicy
          </Link>
        </li>
        <li style={{marginBottom: "10px"}}>
          <Link to="/license" style={{color: "#87CEFA", textDecoration: "none"}}>
            License
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
